/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkcssms1;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import javax.swing.JProgressBar;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import com.sun.speech.freetts.*;
/**
 *
 * @author use
 */
public class Forgot_Pass extends javax.swing.JFrame {
Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form Forgot_Pass
     */
    public Forgot_Pass() {
        initComponents();
         conn = (Connection) MysqlConnection.ConnectDB();
         Info.setVisible(true);
                security.setVisible(false);
                newpass.setVisible(false);
                refresh_admin();
                 seticon();
    }
 public void refresh_admin() {
        try {
            //DateAdded,Supplier,ProductID,Description,Category,Quantity,Value,Price,Sale
            String sql = "SELECT AccountID,Name FROM tbl_admin";
            pst = (PreparedStatement) (java.sql.PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            tbl_list.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
     
     
     public void refresh_user() {
        try {
            //DateAdded,Supplier,ProductID,Description,Category,Quantity,Value,Price,Sale
            String sql = "SELECT AccountID,Name FROM tbl_user";
            pst = (PreparedStatement) (java.sql.PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            tbl_list.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private static final String VOICENAME="kevin16";
    Voice voice;
     VoiceManager vm = VoiceManager.getInstance();
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Info = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AccName = new javax.swing.JTextField();
        AccID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_list = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        select = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        security = new javax.swing.JPanel();
        key = new javax.swing.JLabel();
        contact17 = new javax.swing.JLabel();
        nq1 = new javax.swing.JLabel();
        contact20 = new javax.swing.JLabel();
        contact19 = new javax.swing.JLabel();
        na1 = new javax.swing.JTextField();
        contact14 = new javax.swing.JLabel();
        nq2 = new javax.swing.JLabel();
        na2 = new javax.swing.JTextField();
        contact21 = new javax.swing.JLabel();
        nq3 = new javax.swing.JLabel();
        na3 = new javax.swing.JTextField();
        contact23 = new javax.swing.JLabel();
        contact24 = new javax.swing.JLabel();
        contact13 = new javax.swing.JLabel();
        contact16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        newpass = new javax.swing.JPanel();
        uname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        repeatepass = new javax.swing.JPasswordField();
        newpass1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forgot Password");
        setUndecorated(true);

        jPanel2.setLayout(new java.awt.CardLayout());

        Info.setBackground(new java.awt.Color(255, 255, 255));
        Info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 97, 139)));
        Info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Info.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 40, 40));

        AccName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccNameActionPerformed(evt);
            }
        });
        Info.add(AccName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 290, 40));

        AccID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Info.add(AccID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 290, 40));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbl_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbl_list.setGridColor(new java.awt.Color(204, 204, 204));
        tbl_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_list);

        Info.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 220, 390));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Account Name:");
        Info.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("AccountID:");
        Info.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Info.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 90, 30));

        select.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        select.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "User" }));
        select.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                selectPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        Info.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 30));

        jPanel1.setBackground(new java.awt.Color(2, 97, 139));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FORGOT PASSWORD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel7)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Info.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 360, 30));

        jPanel2.add(Info, "card2");

        security.setBackground(new java.awt.Color(255, 255, 255));
        security.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 97, 139)));
        security.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        key.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        key.setForeground(new java.awt.Color(0, 51, 102));
        key.setText("Account Security");
        security.add(key, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        contact17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contact17.setForeground(new java.awt.Color(102, 102, 102));
        contact17.setText("Personal Verification Question 1");
        security.add(contact17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, 20));

        nq1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nq1.setText("Question");
        security.add(nq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, 20));

        contact20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contact20.setText("Question:");
        security.add(contact20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));

        contact19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contact19.setText("Answere:");
        security.add(contact19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 20));

        na1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        security.add(na1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 400, -1));

        contact14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contact14.setForeground(new java.awt.Color(102, 102, 102));
        contact14.setText("Personal Verification Question 2");
        security.add(contact14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, 20));

        nq2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nq2.setText("Question");
        security.add(nq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, 20));

        na2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        security.add(na2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 400, -1));

        contact21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contact21.setForeground(new java.awt.Color(102, 102, 102));
        contact21.setText("Personal Verification Question 3");
        security.add(contact21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, 20));

        nq3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nq3.setText("Question");
        security.add(nq3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, 20));

        na3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        security.add(na3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 400, -1));

        contact23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contact23.setText("Answere:");
        security.add(contact23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 20));

        contact24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contact24.setText("Question:");
        security.add(contact24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 20));

        contact13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contact13.setText("Answere:");
        security.add(contact13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 20));

        contact16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contact16.setText("Question:");
        security.add(contact16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 20));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        security.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 90, 30));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        security.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 40, 40));

        jPanel2.add(security, "card3");

        newpass.setBackground(new java.awt.Color(255, 255, 255));
        newpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 97, 139)));
        newpass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newpass.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 360, 40));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("Repeate Password");
        newpass.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("Username");
        newpass.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel9.setText("New Password");
        newpass.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        repeatepass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newpass.add(repeatepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 360, 40));

        newpass1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newpass.add(newpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 360, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        newpass.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 140, 30));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        newpass.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 40, 40));

        jPanel2.add(newpass, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void AccNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      voice = vm.getVoice(VOICENAME);
     voice.allocate();
        try{
            String sql = "SELECT * FROM tbl_admin where AccountID =? and Name=?";
            pst = (PreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, AccID.getText());
            pst.setString(2, AccName.getText());

            rs = pst.executeQuery();
            if (rs.next()) {

                pst = (PreparedStatement) conn.prepareStatement("SELECT * FROM tbl_admin WHERE AccountID= '" + AccID.getText() + "' and Name= '" + AccName.getText() + "' ");
                rs = pst.executeQuery();
                if (rs.next()) {
                    String add1 = rs.getString("Q1");
                    String add2 = rs.getString("Q2");
                    String add3 = rs.getString("Q3");
                    nq1.setText(add1);
                    nq2.setText(add2);
                    nq3.setText(add3);

                }
                Info.setVisible(false);
                security.setVisible(true);
                newpass.setVisible(false);
                key.setText("Admin Account Security");
            }else{

                String sql1 = "SELECT * FROM tbl_user where AccountID =? and Name=?";
                pst = (PreparedStatement) conn.prepareStatement(sql1);
                pst.setString(1, AccID.getText());
                pst.setString(2, AccName.getText());

                rs = pst.executeQuery();
                if (rs.next()) {

                    pst = (PreparedStatement) conn.prepareStatement("SELECT * FROM tbl_user WHERE AccountID= '" + AccID.getText() + "' and Name= '" + AccName.getText() + "' ");
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        String add1 = rs.getString("Q1");
                        String add2 = rs.getString("Q2");
                        String add3 = rs.getString("Q3");
                        nq1.setText(add1);
                        nq2.setText(add2);
                        nq3.setText(add3);

                    }
                    Info.setVisible(false);
                    security.setVisible(true);
                    newpass.setVisible(false);
                    key.setText("User Account Security");
                }else{
                    voice.speak("Account ID/Name not exist on the database please check from table!!!");
                    JOptionPane.showMessageDialog(null, "Account ID/Name not exist on the database!!!");
                }
            }
        }catch(SQLException x) {
            JOptionPane.showMessageDialog(null, x);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void selectPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_selectPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (select.getSelectedItem().equals("Admin")){
            refresh_admin();
        }else{
            refresh_user();
        }

    }//GEN-LAST:event_selectPopupMenuWillBecomeInvisible

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         voice = vm.getVoice(VOICENAME);
     voice.allocate();
        if (key.getText().equals("Admin Account Security")){
            try{
                String sql = "SELECT * FROM tbl_admin where AccountID =? and Q1=? and A1=?";
                pst = (PreparedStatement) conn.prepareStatement(sql);
                pst.setString(1, AccID.getText());
                pst.setString(2, nq1.getText());
                pst.setString(3, na1.getText());

                rs = pst.executeQuery();
                if (rs.next()) {
                    //q1
                    String sq2 = "SELECT * FROM tbl_admin where AccountID =? and Q2=? and A2=?";
                    pst = (PreparedStatement) conn.prepareStatement(sq2);
                    pst.setString(1, AccID.getText());
                    pst.setString(2, nq2.getText());
                    pst.setString(3, na2.getText());

                    rs = pst.executeQuery();
                    if (rs.next()) {
                        //q2
                        String sq3 = "SELECT * FROM tbl_admin where AccountID =? and Q3=? and A3=?";
                        pst = (PreparedStatement) conn.prepareStatement(sq3);
                        pst.setString(1, AccID.getText());
                        pst.setString(2, nq3.getText());
                        pst.setString(3, na3.getText());

                        rs = pst.executeQuery();
                        if (rs.next()) {
                            Info.setVisible(false);
                            security.setVisible(false);
                            newpass.setVisible(true);
                        }else{
                            voice.speak("Incorrect Answere Question number 3!!");
                            JOptionPane.showMessageDialog(null, "Incorrect Answere Question number 3!!");
                        }

                    }else{
                        voice.speak("Incorrect Answere Question number 2!!");
                        JOptionPane.showMessageDialog(null, "Incorrect Answere Question number 2!!");
                    }

                }else{
                    voice.speak("Incorrect Answere Question number 1!!");
                    JOptionPane.showMessageDialog(null, "Incorrect Answere Question number 1!!");
                }
            }catch(SQLException x) {
                JOptionPane.showMessageDialog(null, x);
            }
        }else{
            try{
                String sql = "SELECT * FROM tbl_user where AccountID =? and Q1=? and A1=?";
                pst = (PreparedStatement) conn.prepareStatement(sql);
                pst.setString(1, AccID.getText());
                pst.setString(2, nq1.getText());
                pst.setString(3, na1.getText());

                rs = pst.executeQuery();
                if (rs.next()) {
                    //q1
                    String sq2 = "SELECT * FROM tbl_user where AccountID =? and Q2=? and A2=?";
                    pst = (PreparedStatement) conn.prepareStatement(sq2);
                    pst.setString(1, AccID.getText());
                    pst.setString(2, nq2.getText());
                    pst.setString(3, na2.getText());

                    rs = pst.executeQuery();
                    if (rs.next()) {
                        //q2
                        String sq3 = "SELECT * FROM tbl_user where AccountID =? and Q3=? and A3=?";
                        pst = (PreparedStatement) conn.prepareStatement(sq3);
                        pst.setString(1, AccID.getText());
                        pst.setString(2, nq3.getText());
                        pst.setString(3, na3.getText());

                        rs = pst.executeQuery();
                        if (rs.next()) {
                            Info.setVisible(false);
                            security.setVisible(false);
                            newpass.setVisible(true);
                        }else{
                            voice.speak("Incorrect Answere Question number 3!!");
                            JOptionPane.showMessageDialog(null, "Incorrect Answere Question number 3!!");
                        }

                    }else{
                        voice.speak("Incorrect Answere Question number 2!!");
                        JOptionPane.showMessageDialog(null, "Incorrect Answere Question number 2!!");
                    }

                }else{
                    voice.speak("Incorrect Answere Question number 1!!");
                    JOptionPane.showMessageDialog(null, "Incorrect Answere Question number 1!!");
                }
            }catch(SQLException x) {
                JOptionPane.showMessageDialog(null, x);
            }

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        voice = vm.getVoice(VOICENAME);
     voice.allocate();
        if(newpass1.getText().equals(repeatepass.getText())){
            try{
                String sql = "SELECT * FROM tbl_admin where AccountID =? and Name=? and Username =?";
                pst = (PreparedStatement) conn.prepareStatement(sql);
                pst.setString(1, AccID.getText());
                pst.setString(2, AccName.getText());
                pst.setString(3, uname.getText());

                rs = pst.executeQuery();
                if (rs.next()) {

                    pst=(com.mysql.jdbc.PreparedStatement) conn.prepareStatement("UPDATE tbl_admin SET Password=? WHERE Username='"+uname.getText()+"' and AccountID='"+AccID.getText()+"'  and Name='"+AccName.getText()+"'");

                    pst.setString(1,newpass1.getText());

                    int admin_update = pst.executeUpdate();

                    if (admin_update!=0){
                        try{
                            jButton3.setText("Saving...");
                            Thread.sleep(40);
                            voice.speak("Admin Account New Password Saved Successfully");
                            JOptionPane.showMessageDialog(null, "Admin Account New Password Saved");
                            this.dispose();
                        }catch(Exception x){
                            JOptionPane.showMessageDialog(null, x);
                        }
                    }

                }else{

                    String sq2 = "SELECT * FROM tbl_user where AccountID =? and Name=? and Username =?";
                    pst = (PreparedStatement) conn.prepareStatement(sq2);
                    pst.setString(1, AccID.getText());
                    pst.setString(2, AccName.getText());
                    pst.setString(3, uname.getText());

                    rs = pst.executeQuery();
                    if (rs.next()) {

                        pst=(com.mysql.jdbc.PreparedStatement) conn.prepareStatement("UPDATE tbl_user SET Password=? WHERE Username='"+uname.getText()+"' and AccountID='"+AccID.getText()+"'  and Name='"+AccName.getText()+"'");

                        pst.setString(1,newpass1.getText());

                        int admin_update1 = pst.executeUpdate();

                        if (admin_update1!=0){
                            try{
                                jButton3.setText("Saving...");
                                Thread.sleep(40);
                                voice.speak("User Account New Password Saved Successfully");
                                JOptionPane.showMessageDialog(null, "User Account New Password Saved");
                                this.dispose();

                            }catch(Exception x){
                                JOptionPane.showMessageDialog(null, x);
                            }
                        }

                    }else{
                        voice.speak("Inccorect Username Please Check!");
                        JOptionPane.showMessageDialog(null, "Inccorect Username!");

                    }

                }
            }catch(SQLException x) {
                JOptionPane.showMessageDialog(null, x);
            }
        }else{
            voice.speak("Inccorect Password Match Please Check!");
            JOptionPane.showMessageDialog(null, "Inccorect Password Match!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void tbl_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_listMouseClicked
        // TODO add your handling code here:
        int z = tbl_list.getSelectedRow();
                DefaultTableModel model = (DefaultTableModel) tbl_list.getModel();
                AccID.setText(model.getValueAt(z, 0).toString());
                AccName.setText(model.getValueAt(z, 1).toString());
    }//GEN-LAST:event_tbl_listMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgot_Pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgot_Pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgot_Pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgot_Pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgot_Pass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccID;
    private javax.swing.JTextField AccName;
    private javax.swing.JPanel Info;
    private javax.swing.JLabel contact13;
    private javax.swing.JLabel contact14;
    private javax.swing.JLabel contact16;
    private javax.swing.JLabel contact17;
    private javax.swing.JLabel contact19;
    private javax.swing.JLabel contact20;
    private javax.swing.JLabel contact21;
    private javax.swing.JLabel contact23;
    private javax.swing.JLabel contact24;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel key;
    private javax.swing.JTextField na1;
    private javax.swing.JTextField na2;
    private javax.swing.JTextField na3;
    private javax.swing.JPanel newpass;
    private javax.swing.JPasswordField newpass1;
    private javax.swing.JLabel nq1;
    private javax.swing.JLabel nq2;
    private javax.swing.JLabel nq3;
    private javax.swing.JPasswordField repeatepass;
    private javax.swing.JPanel security;
    private javax.swing.JComboBox select;
    private javax.swing.JTable tbl_list;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
private void seticon() {
      setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("PKALOGO.png")));
    }

}
