/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkcssms1;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class newcustomer extends javax.swing.JFrame {
Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form newcustomer
     */
    public newcustomer() {
        initComponents();
         conn = MysqlConnection.ConnectDB();
         seticon();
    }
public void clear(){
cusid.setText("[Click To Auto Generate ID]");
cusname.setText("");
cusage.setText("");
cusstreet.setText("");
cuscity.setText("");
cuscontact.setText("");
cusemail.setText("");
cuswalkin.setSelected(false);
cusregular.setSelected(false);



} 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cusid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cusname = new javax.swing.JTextField();
        cusgender = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cusstreet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cusage = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cuscity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cuscontact = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cusemail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cusregular = new javax.swing.JCheckBox();
        cuswalkin = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DREAMS TILE CENTER - New Customer");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu_icon/user (1).png"))); // NOI18N
        jLabel8.setText("  NEW CUSTOMER");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Customer ID");
        jLabel1.setToolTipText("");

        cusid.setEditable(false);
        cusid.setBackground(new java.awt.Color(255, 255, 255));
        cusid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cusid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cusid.setText("[Click To Auto Generate ID]");
        cusid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cusidMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Street");
        jLabel2.setToolTipText("");

        cusname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cusname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cusname.setToolTipText("");

        cusgender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cusgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Fullname");
        jLabel3.setToolTipText("");

        cusstreet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cusstreet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cusstreet.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Gender");
        jLabel4.setToolTipText("");

        cusage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cusage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cusage.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Age");
        jLabel5.setToolTipText("");

        cuscity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cuscity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cuscity.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("City");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Contact");
        jLabel7.setToolTipText("");

        cuscontact.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cuscontact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cuscontact.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Customer Status");
        jLabel9.setToolTipText("");

        cusemail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cusemail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cusemail.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Email");
        jLabel10.setToolTipText("");

        cusregular.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cusregular.setText("Regular");
        cusregular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusregularActionPerformed(evt);
            }
        });

        cuswalkin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cuswalkin.setText("Walk In");
        cuswalkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuswalkinActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cusid, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(cusname, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(87, 87, 87)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cusgender, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cusage, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(cusstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(cuscity, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cuscontact, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(cusemail, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuswalkin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cusregular, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(cusid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(cusname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cusgender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cusage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(cusstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addComponent(cuscity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addGap(5, 5, 5)
                .addComponent(cuscontact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel10)
                .addGap(5, 5, 5)
                .addComponent(cusemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cuswalkin)
                        .addGap(7, 7, 7)
                        .addComponent(cusregular)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cusidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusidMouseClicked
        // TODO add your handling code here:
        if (cusid.getText().equals("[Click To Auto Generate ID]")){
            Date d = new Date();
            SimpleDateFormat s = new SimpleDateFormat("hmmss");
            SimpleDateFormat st = new SimpleDateFormat("MMddyyyy");
            cusid.setText("ID"+st.format(d)+s.format(d));
        }else{}
    }//GEN-LAST:event_cusidMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         
        if (cusid.getText().equals("[Click To Auto Generate ID]")){
        JOptionPane.showMessageDialog(null,"Invalid ID!!");
        }else{
         try {
         if (cuswalkin.isSelected()){
                            String sql1 = "INSERT INTO tbl_customer VALUES (?,?,?,?,?,?,?,?,?,?)";

                            pst = (PreparedStatement) conn.prepareStatement(sql1);
                            pst.setString(1,cusid.getText());
                            pst.setString(2,cusname.getText());
                            pst.setString(3,(String)cusgender.getSelectedItem());
                            pst.setString(4,cusage.getText());
                            pst.setString(5,cusstreet.getText());
                            pst.setString(6,cuscity.getText());
                            pst.setString(7,cuscontact.getText());
                            pst.setString(8,cusemail.getText());
                            pst.setString(9,cuswalkin.getText());
                            pst.setString(10,"Active");
                           int add = pst.executeUpdate();
                            if(add!=0){
                                JOptionPane.showMessageDialog(null,"New Walkin Customer Saved!!");
                                clear();
                            } else{
                                JOptionPane.showMessageDialog(null,"Failed to Store!");
                                clear();
                            }
         }else if (cusregular.isSelected()){
         
                            String sql1 = "INSERT INTO tbl_customer VALUES (?,?,?,?,?,?,?,?,?,?)";

                            pst = (PreparedStatement) conn.prepareStatement(sql1);
                            pst.setString(1,cusid.getText());
                            pst.setString(2,cusname.getText());
                            pst.setString(3,(String)cusgender.getSelectedItem());
                            pst.setString(4,cusage.getText());
                            pst.setString(5,cusstreet.getText());
                            pst.setString(6,cuscity.getText());
                            pst.setString(7,cuscontact.getText());
                            pst.setString(8,cusemail.getText());
                            pst.setString(9,cusregular.getText());
                            pst.setString(10,"Active");
                           int add = pst.executeUpdate();
                            if(add!=0){
                                JOptionPane.showMessageDialog(null,"New Regular Customer Saved!!");
                            } else{
                                JOptionPane.showMessageDialog(null,"Failed to Store!");
                            }
             
             
         }else{
          JOptionPane.showMessageDialog(null,"Please Select Customer Status");
         }
             
         }catch(SQLException e){
           JOptionPane.showMessageDialog(null, e);
         }
          
          
          }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cuswalkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuswalkinActionPerformed
        // TODO add your handling code here:
        cusregular.setSelected(false);
    }//GEN-LAST:event_cuswalkinActionPerformed

    private void cusregularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusregularActionPerformed
        // TODO add your handling code here:
        cuswalkin.setSelected(false);
    }//GEN-LAST:event_cusregularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newcustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cusage;
    private javax.swing.JTextField cuscity;
    private javax.swing.JTextField cuscontact;
    private javax.swing.JTextField cusemail;
    private javax.swing.JComboBox<String> cusgender;
    private javax.swing.JTextField cusid;
    private javax.swing.JTextField cusname;
    private javax.swing.JCheckBox cusregular;
    private javax.swing.JTextField cusstreet;
    private javax.swing.JCheckBox cuswalkin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
private void seticon() {
      setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("user(1).png")));
    }
}
